# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9ea5b5056f2a30e80a8f8c437fd003c36ad8faf2be5e09d2803cee39313893fe0b660e5405f4f6bc76d5115eae1808ef351c9682c34fdc66f5e5df32fdfc7e

test:
  secret_key_base: 2022ebce1062761b3566c8c7723f6fb569ccd42e8b6329d6b46203f844cbcc1b78be9a4d1a42b9947f651423250504abcdb03e49ca5b5451b5d79863b681a5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
